name: Validate
on:
 push:
   branches-ignore:
   - master

jobs:
  validate:
    strategy:
      matrix:
        type: [format, test, build]

    runs-on: ubuntu-latest
    steps:

    - uses: actions/checkout@v4
    - uses: actions/setup-node@v4
    - run: npm ci

    - if: matrix.type == 'format'
      run: npx prettier --check 'src/**/*.ts' 'src/**/*.tsx'

    - if: matrix.type == 'test'
      run: npx vitest

    - if: matrix.type == 'build'
      run: npx vite build
